version: '2'

services:
  node:
    image: 'node:12'
    volumes:
      - '~/.npm:/.npm'
      - './:/app'
    working_dir: /app
    command: npm run dev
    environment:
      - PORT
      - API_URL
    ports:
      - '${PORT}:4000'

  client:
    image: 'node:12'
    volumes:
      - '~/.npm:/.npm'
      - './client-demo:/app'
    working_dir: /app
    command: npm run serve
    environment:
      - CLIENT_PORT
      - VUE_APP_GRAPHQL_URL
    ports:
      - '${CLIENT_PORT}:8080'
