version: '2'

services:
  node:
    image: 'node:12'
    volumes:
      - '~/.npm:/.npm'
      - './:/app'
    working_dir: /app
    command: npm run dev
    environment:
      - PORT
    ports:
      - '${PORT}:4000'
